// <auto-generated />
namespace ElearningProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class migaddabouttable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migaddabouttable));
        
        string IMigrationMetadata.Id
        {
            get { return "202311251448535_mig-add-abouttable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
